(function(o){function V(i,e){var j=/^\w+\:\/\//,r;if(typeof i!=u)i="";if(typeof e!=u)e="";r=(j.test(i)?"":e)+i;return(j.test(r)?"":r.charAt(0)==="/"?fa:ga)+r}function E(i,e){function j(a,b){if(a[B]&&a[B]!==n&&a[B]!=="loaded"||b[k])return l;a[I]=a[J]=g;return m}function r(a,b,d){if((d=!!d)||j(a,b)){b[k]=m;for(var c in y)if(y[C](c)&&!y[c][k])return;ha=m;ia()}}function F(a){if(G.call(a[z])===O){a[z]();a[z]=g}}function ta(a,b){if(j(a,b)){b[t]=m;f(function(){v[b[p]].removeChild(a);F(b)},0)}}function ua(a,
b){if(a[B]===4){a[J]=K;b[t]=m;f(function(){F(b)},0)}}function aa(a,b,d,c,w,A){var P=a[p];f(function(){if("item"in v[P]){if(!v[P][0]){f(arguments.callee,25);return}v[P]=v[P][0]}var D=q.createElement(L);if(typeof d==u)D.type=d;if(typeof c==u)D.charset=c;if(G.call(w)===O){D[I]=D[J]=function(){w(D,a)};D.src=b;if(ja)D.async=l}v[P].insertBefore(D,P===x?v[P].firstChild:g);if(typeof A==u){D.text=A;r(D,a,m)}},0)}function ka(a,b,d,c){ba[a[Q]]=m;aa(a,b,d,c,r)}function la(a,b,d,c){var w=arguments;if(H&&a[t]==
g){a[t]=l;aa(a,b,R,c,ta)}else if(!H&&a[t]!=g&&!a[t])a[z]=function(){la.apply(g,w)};else H||ka.apply(g,w)}function ma(a,b,d,c){var w=arguments,A;if(H&&a[t]==g){a[t]=l;A=a.xhr=h?new h("Microsoft.XMLHTTP"):new o.XMLHttpRequest;A[J]=function(){ua(A,a)};A.open("GET",b);A.send("")}else if(!H&&a[t]!=g&&!a[t])a[z]=function(){ma.apply(g,w)};else if(!H){ba[a[Q]]=m;aa(a,b,d,c,g,a.xhr.responseText);a.xhr=g}}function na(a){if(a.allowDup==g)a.allowDup=e.dupe;var b=a.type,d=a.charset,c=a.allowDup;a=V(a.src,va);
var w=V(a).indexOf(fa)===0;if(typeof d!=u)d=g;c=!!c;if(c=!c){if(!(c=ba[a]!=g)){if(!(c=H&&y[a]))a:{for(var A=-1;c=wa[++A];)if(typeof c.src==u&&a===V(c.src)&&c.type!==R){c=m;break a}c=l}c=c}c=c}if(c)y[a]!=g&&y[a][t]&&!y[a][k]&&w&&r(g,y[a],m);else{if(y[a]==g)y[a]={};c=y[a];if(c[p]==g)c[p]=xa;c[k]=l;c[Q]=a;ca=m;if(!Y&&oa&&w)ma(c,a,b,d);else!Y&&pa?la(c,a,b,d):ka(c,a,b,d)}}function da(a){i&&!Y&&Z.push(a);if(!i||X)a()}function qa(a){var b=[],d;for(d=-1;++d<a.length;)if(G.call(a[d])===W)b=b.concat(qa(a[d]));
else b[b.length]=a[d];return b}i=!!i;if(e==g)e=S;var ha=l,X=i&&e[T],pa=X&&e.cache,Y=X&&e.order,oa=X&&e.xhr,ya=e[U],xa=e.which,va=e.base,ia=K,ca=l,$,H=m,y={},Z=[],ea=g;X=pa||oa||Y;$={script:function(){s(ea);var a=qa(arguments),b=$,d;if(ya)for(d=-1;++d<a.length;){if(d===0)da(function(){na(typeof a[0]==u?{src:a[0]}:a[0])});else b=b.script(a[d]);b=b.wait()}else da(function(){for(d=-1;++d<a.length;)na(typeof a[d]==u?{src:a[d]}:a[d])});ea=f(function(){H=l},5);return b},wait:function(a){s(ea);H=l;G.call(a)===
O||(a=K);var b=E(m,e),d=b.trigger,c=function(){try{a()}catch(A){}d()};delete b.trigger;var w=function(){if(ca&&!ha)ia=c;else c()};i&&!ca?Z.push(w):da(w);return b}};if(i)$.trigger=function(){for(var a,b=-1;a=Z[++b];)a();Z=[]};return $}function M(i){var e,j={},r={UseCachePreload:"cache",UseLocalXHR:"xhr",UsePreloading:T,AlwaysPreserveOrder:U,AllowDuplicates:"dupe"},F={AppendTo:p,BasePath:"base"};for(e in r)F[e]=r[e];j.order=!!S.order;for(e in F)if(F[C](e)&&S[F[e]]!=g)j[F[e]]=i[e]!=g?i[e]:S[F[e]];for(e in r)if(r[C](e))j[r[e]]=
!!j[r[e]];if(!j[T])j.cache=j.order=j.xhr=l;j.which=j.which===x||j.which===N?j.which:x;return j}var u="string",x="head",N="body",L="script",B="readyState",t="preloaddone",z="loadtrigger",Q="srcuri",T="preload",n="complete",k="done",p="which",U="preserve",J="onreadystatechange",I="onload",C="hasOwnProperty",R="script/cache",O="[object Function]",W="[object Array]",g=null,m=true,l=false,q=o.document,h=o.ActiveXObject,f=o.setTimeout,s=o.clearTimeout,G=Object.prototype.toString,K=function(){},v={},ba=
{},ga=/^[^?#]*\//.exec(o.location.href)[0],fa=/^\w+\:\/\/\/?[^\/]+/.exec(ga)[0],wa=q.getElementsByTagName(L),ra=o.opera&&G.call(o.opera)=="[object Opera]",sa="MozAppearance"in q.documentElement.style,ja=q.createElement(L).async===true,S={cache:!(sa||ra),order:sa||ra||ja,xhr:m,dupe:m,base:"",which:x};S[U]=l;S[T]=m;v[x]=q.head||q.getElementsByTagName(x);v[N]=q.getElementsByTagName(N);o.$LAB={setGlobalDefaults:function(i){S=M(i)},setOptions:function(i){return E(l,M(i))},script:function(){return E().script.apply(g,
arguments)},wait:function(){return E().wait.apply(g,arguments)}};(function(i,e,j){if(q[B]==g&&q[i]){q[B]="loading";q[i](e,j=function(){q.removeEventListener(e,j,l);q[B]=n},l)}})("addEventListener","DOMContentLoaded")})(window);
(function(o){function V(n){var k=[],p;for(p=-1;++p<n.length;)if(Q.call(n[p])==="[object Array]")k=k.concat(V(n[p]));else k[k.length]=n[p];return k}function E(n,k,p){function U(){try{g()}catch(h){}m()}function J(){t(l);if(!q){q=N;var h,f,s,G,K,v=[];for(h=0;h<O.length;h++){s=O[h];f=s.test;K=L;if(typeof f===u){G=f.split(".");current=o;for(f=0;f<G.length;f++){current=current[G[f]];if(typeof current==="undefined"){K=N;break}}}else if(Q.call(f)==="[object Function]")K=!f(s);if(K)v.push(typeof s.alt===u?
{src:s.alt,type:s.type,charset:s.charset}:s.alt)}v.length?M.setOptions(k).script(v).wait(U):U()}}k=k||{};k[x]=k[x]||T;var I,C,R=[],O=[],W=L,g=z,m=z,l,q=L;C={script:function(){t(l);var h=V(arguments),f;for(f=0;f<h.length;f++)if(typeof h[f]!==u&&h[f].alt&&h[f].test){O.push(h[f]);W=N}f=function(){I=(I||(p?p():M.setOptions(k))).script.apply(null,h)};n?R.push(f):f();if(W&&!n)l=B(J,k[x]);return C},wait:function(h){g=Q.call(h)==="[object Function]"?h:z;var f=U;h=n;var s;if(W){f=J;h=N}h=E(h,k,h?null:function(){return I});
m=h.trigger||z;delete h.trigger;s=function(){I=(I||(p?p():M.setOptions(k))).wait(f)};n?R.push(s):s();return h}};C.block=C.wait;if(n)C.trigger=function(){for(var h,f=-1;h=R[++f];)h();R=[];if(W)l=B(J,k[x]);else{m();triggerNextChange=z}};return C}var M=o.$LAB;if(M){var u="string",x="CDNWaitTime",N=true,L=false,B=o.setTimeout,t=o.clearTimeout,z=function(){},Q=Object.prototype.toString,T=5E3;o.$LAB={setGlobalDefaults:function(n){if(n[x])T=n[x];M.setGlobalDefaults(n)},setOptions:function(n){return E(L,
n)},script:function(){return E().script.apply(null,arguments)},wait:function(){return E().wait.apply(null,arguments)}};o.$LAB.block=o.$LAB.wait}})(window);