(function(l){function T(b){return ca(b).indexOf(ja)===0}function F(b){for(var c,f=-1;c=wa[++f];)if(typeof c.src===p&&b===ca(c.src)&&c.type!==M)return k;return m}function G(b,c){function f(a,d){if(a[s]&&a[s]!==W&&a[s]!=="loaded"||d[N])return m;a[O]=a[H]=g;return k}function y(a,d,i){if((i=!!i)||f(a,d)){d[N]=k;for(var j in w)if(w[z](j)&&!w[j][N])return;ka=k;la()}}function A(a){if(da(a[I])){a[I]();a[I]=g}}function xa(a,d){if(f(a,d)){d[q]=k;J(function(){t[d[K]].removeChild(a);A(d)},0)}}function ya(a,d){if(a[s]===
4){a[H]=n;d[q]=k;J(function(){A(d)},0)}}function ea(a,d,i,j,u,B){var P=a[K];J(function(){if("item"in t[P]){if(!t[P][0]){J(arguments.callee,25);return}t[P]=t[P][0]}var C=v.createElement(X);C.type=i;if(typeof j===p)C.charset=j;if(da(u)){C[O]=C[H]=function(){u(C,a)};C.src=d}t[P].insertBefore(C,P===x?t[P].firstChild:g);if(typeof B===p){C.text=B;y(C,a,k)}},0)}function ma(a,d,i,j){L[a[o]]=k;ea(a,d,i,j,y)}function na(a,d,i,j){var u=arguments;if(D&&a[q]==g){a[q]=m;ea(a,d,M,j,xa)}else if(!D&&a[q]!=g&&!a[q])a[I]=
function(){na.apply(g,u)};else D||ma.apply(g,u)}function oa(a,d,i,j){var u=arguments,B;if(D&&a[q]==g){a[q]=m;B=a.xhr=Q?new Q("Microsoft.XMLHTTP"):new l.XMLHttpRequest;B[H]=function(){ya(B,a)};B.open("GET",d);B.send("")}else if(!D&&a[q]!=g&&!a[q])a[I]=function(){oa.apply(g,u)};else if(!D){L[a[o]]=k;ea(a,d,i,j,g,a.xhr.responseText);a.xhr=g}}function pa(a){if(a.allowDup==g)a.allowDup=c.dupe;var d=a.type,i=a.charset,j=a.allowDup;a=ca(a.src,za);var u=T(a);if(typeof d!==p)d="text/javascript";if(typeof i!==
p)i=g;j=!!j;if(!j&&(L[a]!=g||D&&w[a]||F(a)))w[a]!=g&&w[a][q]&&!w[a][N]&&u&&y(g,w[a],k);else{if(w[a]==g)w[a]={};j=w[a];if(j[K]==g)j[K]=Aa;j[N]=m;j[o]=a;fa=k;if(!aa&&qa&&u)oa(j,a,d,i);else!aa&&ra?na(j,a,d,i):ma(j,a,d,i)}}function sa(a){ga.push(a)}function ha(a){b&&!aa&&sa(a);if(!b||Y)a()}b=!!b;if(c==g)c=R;var ka=m,Y=b&&c[r],ra=Y&&c.cache,aa=Y&&c.order,qa=Y&&c.xhr,Ba=c[S],Aa=c.which,za=c.base,la=n,fa=m,U,D=k,w={},ga=[],ia=g;Y=ra||qa||aa;U={script:function(){Z(ia);var a=ta(arguments),d=U,i;if(Ba)for(i=
-1;++i<a.length;){if(i===0)ha(function(){pa(typeof a[0]===p?{src:a[0]}:a[0])});else d=d.script(a[i]);d=d.wait()}else ha(function(){for(i=-1;++i<a.length;)pa(typeof a[i]===p?{src:a[i]}:a[i])});ia=J(function(){D=m},5);return d},wait:function(a){Z(ia);D=m;da(a)||(a=n);var d=G(k,c),i=d.trigger,j=function(){try{a()}catch(B){}i()};delete d.trigger;var u=function(){if(fa&&!ka)la=j;else j()};b&&!fa?sa(u):ha(u);return d}};U.block=U.wait;if(b)U.trigger=function(){for(var a,d=-1;a=ga[++d];)a();ga=[]};return U}
function E(b){var c,f={},y={UseCachePreload:"cache",UseLocalXHR:"xhr",UsePreloading:r,AlwaysPreserveOrder:S,AllowDuplicates:"dupe"},A={AppendTo:K,BasePath:"base"};for(c in y)A[c]=y[c];f.order=!!R.order;for(c in A)if(A[z](c)&&R[A[c]]!=g)f[A[c]]=b[c]!=g?b[c]:R[A[c]];for(c in y)if(y[z](c))f[y[c]]=!!f[y[c]];if(!f[r])f.cache=f.order=f.xhr=m;f.which=f.which===x||f.which===V?f.which:x;return f}var p="string",x="head",V="body",X="script",s="readyState",q="preloaddone",I="loadtrigger",o="srcuri",r="preload",
W="complete",N="done",K="which",S="preserve",H="onreadystatechange",O="onload",z="hasOwnProperty",M="script/cache",g=null,k=true,m=false,v=l.document,Q=l.ActiveXObject,J=l.setTimeout,Z=l.clearTimeout,e=function(b){return v.getElementsByTagName(b)},h=Object.prototype.toString,n=function(){},t={},L={},$=/^[^?#]*\//.exec(l.location.href)[0],ja=/^\w+\:\/\/\/?[^\/]+/.exec($)[0],wa=e(X),ba={},ua=l.opera&&h.call(l.opera)=="[object Opera]",va=function(b){b[b]=b+"";return b[b]!=b+""}(new String("__count__")),
R={cache:!(va||ua),order:va||ua,xhr:k,dupe:k,base:"",which:x};R[S]=m;R[r]=k;t[x]=e(x);t[V]=e(V);var da=ba.isFunc=function(b){return h.call(b)==="[object Function]"},ca=ba.canonicalScriptURI=function(b,c){var f=/^\w+\:\/\//;if(typeof b!==p)b="";if(typeof c!==p)c="";b=(f.test(b)?"":c)+b;return(f.test(b)?"":b.charAt(0)==="/"?ja:$)+b},ta=ba.serializeArgs=function(b){var c=[],f;for(f=-1;++f<b.length;)if(h.call(b[f])==="[object Array]")c=c.concat(ta(b[f]));else c[c.length]=b[f];return c};l.$LAB={setGlobalDefaults:function(b){R=
E(b)},setOptions:function(b){return G(m,E(b))},script:function(){return G().script.apply(g,arguments)},wait:function(){return G().wait.apply(g,arguments)},util:ba};l.$LAB.block=l.$LAB.wait;(function(b,c,f){if(v[s]==g&&v[b]){v[s]="loading";v[b](c,f=function(){v.removeEventListener(c,f,m);v[s]=W},m)}})("addEventListener","DOMContentLoaded")})(window);
(function(l){function T(o,r,W){function N(){var e,h,n,t,L,$=[];for(e=0;e<g.length;e++){n=g[e];h=n.test;L=x;if(typeof h===G){t=h.split(".");current=l;for(h=0;h<t.length;h++){current=current[t[h]];if(typeof current==="undefined"){L=p;break}}}else if(q(h))L=!h(n);if(L)$.push(typeof n.alt===G?{src:n.alt,type:n.type,charset:n.charset}:n.alt)}return $}function K(){return O||(W?W.getEng():F.setOptions(r))}function S(){try{m()}catch(e){}v()}function H(){X(Q);if(!Z){Z=p;var e=N();e.length?F.setOptions(r).script(e).wait(S):
S()}}r=r||{};r[E]=r[E]||I;var O,z,M=[],g=[],k=x,m=s,v=s,Q,J=this,Z=x;J.getEng=function(){return O};z={script:function(){X(Q);var e=F.util.serializeArgs(arguments),h;for(h=0;h<e.length;h++)if(typeof e[h]!==G&&e[h].alt&&e[h].test){g.push(e[h]);k=p}h=function(){O=K().script.apply(null,e)};o?M.push(h):h();if(k&&!o)Q=V(H,r[E]);return z},wait:function(e){m=q(e)?e:s;var h=S;e=o;var n;if(k){h=H;e=p}e=T(e,r,e?null:J);v=e.trigger||s;delete e.trigger;n=function(){O=K().wait(h)};o?M.push(n):n();return e}};z.block=
z.wait;if(o)z.trigger=function(){for(var e,h=-1;e=M[++h];)e();M=[];if(k)Q=V(H,r[E]);else{v();triggerNextChange=s}};return z}var F=l.$LAB;if(F){var G="string",E="CDNWaitTime",p=true,x=false,V=l.setTimeout,X=l.clearTimeout,s=function(){},q=F.util.isFunc,I=5E3;l.$LAB={setGlobalDefaults:function(o){if(o[E])I=o[E];F.setGlobalDefaults(o)},setOptions:function(o){return T(x,o)},script:function(){return T().script.apply(null,arguments)},wait:function(){return T().wait.apply(null,arguments)}};l.$LAB.block=
l.$LAB.wait}})(window);